export const SET_SELECTED_CELL = 'SET_SELECTED_CELL';
export const SET_ALL_TABLE_DATA = 'SET_ALL_TABLE_DATA';
export const SET_CELL_DATA = 'SET_CELL_DATA';
export const SET_TYPE_CELL = 'SET_TYPE_CELL';
export const SET_CURRENCY_CELL = 'SET_CURRENCY_CELL';
